export type SetuprErrorSeverity = "info" | "warning" | "error" | "fatal";
export type SetuprErrorCategory =
  | "usage"
  | "project"
  | "env"
  | "auth"
  | "ai"
  | "provider"
  | "runtime"
  | "package-manager"
  | "filesystem"
  | "network"
  | "executor"
  | "tui"
  | "config"
  | "git"
  | "plugin"
  | "migration"
  | "secrets"
  | "docker"
  | "ci"
  | "template"
  | "workspace"
  | "telemetry"
  | "unknown";

export type RecoveryActionKind =
  | "retry"
  | "skip"
  | "continue"
  | "stop"
  | "ask-user"
  | "switch-model"
  | "open-docs"
  | "run-command"
  | "edit-file";

export interface RecoveryAction {
  kind: RecoveryActionKind;
  label: string;
  command?: string;
  details?: string;
  risky?: boolean;
}

export interface SetuprErrorInput {
  code: string;
  category: SetuprErrorCategory;
  severity: SetuprErrorSeverity;
  title: string;
  command?: string;
  subcommand?: string;
  cwd?: string;
  explanation: string;
  details?: string[];
  nextSteps?: string[];
  recovery?: RecoveryAction[];
  canContinue?: boolean;
  forceBehavior?: string;
  exitCode?: number;
  cause?: unknown;
  metadata?: Record<string, unknown>;
}

export interface SetuprError extends SetuprErrorInput {
  code: SetuprErrorCode;
  timestamp: number;
}

export type SetuprErrorCode =
  | "UNKNOWN_COMMAND"
  | "UNKNOWN_SUBCOMMAND"
  | "INVALID_FLAG"
  | "INVALID_FLAG_COMBINATION"
  | "INVALID_CWD"
  | "MISSING_PACKAGE"
  | "INVALID_ARGUMENT"
  | "NON_INTERACTIVE_CONFIRMATION_REQUIRED"
  | "NON_INTERACTIVE_INPUT_REQUIRED"
  | "NO_PROJECT_DETECTED"
  | "MALFORMED_PROJECT_FILE"
  | "PROJECT_CONFIG_INVALID"
  | "MISSING_PACKAGE_JSON"
  | "MISSING_PACKAGE_MANAGER"
  | "MISSING_SCRIPT"
  | "MISSING_RUNTIME"
  | "ENV_TEMPLATE_MISSING"
  | "ENV_FILE_MISSING"
  | "ENV_ALREADY_EXISTS"
  | "ENV_SYNC_FAILED"
  | "ENV_CHECK_FAILED"
  | "ENV_SMART_FAILED"
  | "ENV_WRITE_FAILED"
  | "ENV_INVALID_VALUE"
  | "ENV_DUPLICATE_KEY"
  | "AUTH_PROVIDER_REQUIRED"
  | "AUTH_PROVIDER_UNKNOWN"
  | "AUTH_KEY_MISSING"
  | "AUTH_KEY_EMPTY"
  | "AUTH_KEY_REPLACE_CANCELLED"
  | "AUTH_STORAGE_FAILED"
  | "AUTH_STORAGE_INVALID"
  | "AUTH_MIGRATION_FAILED"
  | "AI_MODEL_REQUIRED"
  | "AI_MODEL_UNKNOWN"
  | "AI_MODEL_UNAVAILABLE"
  | "AI_KEY_MISSING"
  | "AI_PROVIDER_TIMEOUT"
  | "AI_PROVIDER_AUTH_FAILED"
  | "AI_PROVIDER_RATE_LIMITED"
  | "AI_PROVIDER_QUOTA_EXHAUSTED"
  | "AI_PROVIDER_UNAVAILABLE"
  | "AI_PROVIDER_PROTOCOL_ERROR"
  | "AI_PROVIDER_REQUEST_FAILED"
  | "COMMAND_FAILED"
  | "COMMAND_NOT_FOUND"
  | "COMMAND_TIMEOUT"
  | "COMMAND_ABORTED"
  | "PROCESS_ALREADY_RUNNING"
  | "PROCESS_NOT_FOUND"
  | "INSTALL_FAILED"
  | "BUILD_FAILED"
  | "TEST_FAILED"
  | "UPDATE_CHECK_FAILED"
  | "CLEAN_TARGET_FAILED"
  | "CLEAN_MODE_INVALID"
  | "PORT_CHECK_FAILED"
  | "LOCK_STATE_MISSING"
  | "LOG_FILE_MISSING"
  | "OPEN_TARGET_MISSING"
  | "TUI_TERMINAL_TOO_SMALL"
  | "TUI_MOUSE_PROTOCOL_LEFT_ON"
  | "TUI_RENDER_FAILED"
  | "FILESYSTEM_PERMISSION_DENIED"
  | "FILESYSTEM_READ_ONLY"
  | "NETWORK_UNAVAILABLE"
  | "GIT_NOT_INSTALLED"
  | "GIT_NOT_A_REPO"
  | "GIT_DIRTY_WORKING_TREE"
  | "GIT_BRANCH_EXISTS"
  | "GIT_MERGE_CONFLICT"
  | "GIT_PUSH_FAILED"
  | "GIT_REMOTE_MISSING"
  | "GIT_HOOK_FAILED"
  | "GIT_COMMAND_FAILED"
  | "PLUGIN_NOT_FOUND"
  | "PLUGIN_INVALID"
  | "PLUGIN_LOAD_FAILED"
  | "PLUGIN_REGISTRY_FAILED"
  | "MIGRATE_UNSUPPORTED"
  | "MIGRATE_LOCKFILE_CONFLICT"
  | "MIGRATE_FAILED"
  | "CI_PLATFORM_UNKNOWN"
  | "CI_GENERATE_FAILED"
  | "DOCKER_NOT_INSTALLED"
  | "DOCKER_GENERATE_FAILED"
  | "SECRETS_ENCRYPTION_FAILED"
  | "SECRETS_DECRYPTION_FAILED"
  | "SECRETS_KEY_MISSING"
  | "SECRETS_FILE_CORRUPT"
  | "TEMPLATE_NOT_FOUND"
  | "TEMPLATE_FETCH_FAILED"
  | "TEMPLATE_INVALID"
  | "WORKSPACE_NO_PACKAGES"
  | "WORKSPACE_COMMAND_FAILED"
  | "HEALTH_CHECK_FAILED"
  | "SHARE_EXPORT_FAILED"
  | "SHARE_IMPORT_FAILED"
  | "INIT_ALREADY_EXISTS"
  | "INIT_TEMPLATE_FAILED"
  | "TELEMETRY_SEND_FAILED"
  | "UPDATE_AVAILABLE"
  | "UPDATE_FETCH_FAILED"
  | "AI_RETRY_EXHAUSTED"
  | "UNKNOWN_ERROR";
